#!/usr/bin/env python

import argparse    # To parse my arguments

parser = argparse.ArgumentParser(description='Read a file in reverse')
parser.add_argument('filename', type=argparse.FileType('r'), help='name of the file')
parser.add_argument('--limit', '-l', type=int, help='No. of lines to read')
parser.add_argument('--version','-v', action='version', version='%(prog)s 1.0')
args = parser.parse_args()

f = args.filename

# Without argparse.FileType() following would be necessary
# try:
#     f = open(args.filename)
# except IOError as err:
#     print('Error: file not found')
# else:
#     # follwing block

with f:
    limit = args.limit
    lines = f.readlines()
    lines.reverse()
    
    if limit:
        lines = lines[:limit]
    
    for line in lines:
        print(line.strip()[::-1]) # So python knows to reverse read R -> L stripping any whitespaces
# Ending at
# finally:
print('We are finished\n')
